name: CI
# on: push
on: [repository_dispatch, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.14'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fontconfig-config fonts-dejavu-core fonts-dejavu-extra fonts-dejavu-mono fonts-lato fonts-liberation fonts-noto-color-emoji fuse3 hdparm keyutils libattr1:amd64 libaudit-common libbrotli1:amd64 libc-bin libc6:amd64 libfontconfig1:amd64 libfreetype6:amd64 libmagic1t64:amd64 libmecab2:amd64 libpam-runtime libpng16-16t64:amd64 libpython3.14-stdlib:amd64 libsensors-config libtirpc-common libzstd1:amd64 locales login logrotate lsb-release ltrace make man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3.14 rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
          pip install contourpy==1.3.3 cycler==0.12.1 kiwisolver==1.4.9 pre_commit==4.5.1 pyparsing==3.3.2 tomli_w==1.2.0
      - name: Execute Tests
        run: |
          pip install --upgrade pip wheel
          if [[ 'full' == 'full' ]]; then EXTRAS=',stats'; fi
          if [[ 'latest' == 'pinned' ]]; then DEPS='-r ci/deps_pinned.txt'; fi
          pip install .[dev$EXTRAS] $DEPS
          make test
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.14'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fuse3 hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1t64:amd64 libmecab2:amd64 libncursesw6:amd64 libpam-runtime libpython3.14-stdlib:amd64 libsensors-config libtirpc-common libzstd1:amd64 locales login logrotate lsb-release ltrace make man-db media-types multipath-tools nano netbase nftables openssl overlayroot procps python3.14 rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
          pip install contourpy==1.3.3 cycler==0.12.1 kiwisolver==1.4.9 pre_commit==4.5.1 pyparsing==3.3.2 setuptools==80.10.2 tomli_w==1.2.0 uv==0.9.26 wheel==0.46.3
      - name: Execute Tests
        run: |
          pip install mypy~=1.10.0 flake8
          make lint
          make typecheck
