name: CI

# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - ${{ matrix.python-version }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install contourpy==1.3.3 cycler==0.12.1 kiwisolver==1.4.9 pre_commit==4.5.1 tomli_w==1.2.0
      - run: |
          pip install --upgrade pip wheel
          if [[ 'full' == 'full' ]]; then EXTRAS=',stats'; fi
      - run: |
          if [[ 'latest' == 'pinned' ]]; then DEPS='-r ci/deps_pinned.txt'; fi
      - run: |
          pip install .[dev$EXTRAS] $DEPS
      - run: |
          make test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.14'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install contourpy==1.3.3 cycler==0.12.1 kiwisolver==1.4.9 pre_commit==4.5.1 tomli_w==1.2.0 uv==0.9.26
      - run: |
          pip install mypy~=1.10.0 flake8
      - run: |
          make lint
      - run: |
          make typecheck